[general]
static = yes
writeprotect = no
clearglobalvars = no

[globals]
COMPANY_NAME = Loony
SUPPORT_EXT  = 600
MAIN_EXT     = 1000

[internal]

;-----------------------------------------------------
; Extension 1000 — handled by ARI
;-----------------------------------------------------
exten => 1000,1,NoOp(--- Incoming Call to ${MAIN_EXT} ---)
    same => n,Set(VARS=CALLER_ID,CALL_ID,CUSTOM_WELCOME_EVT,COUNTRY,ASTERISK_CHANNEL_ID)
    same => n,Set(CALLER_ID=${CALLERID(num)})
    same => n,Set(CALL_ID=${SIPCALLID})
    same => n,Set(ASTERISK_CHANNEL_ID=${UNIQUEID})
    same => n,Set(CALL_ORIGIN=internal)
    same => n,Set(COUNTRY=IN)
    same => n,Set(GREETING=Hello_from_${COMPANY_NAME})
    same => n,Set(CUSTOM_WELCOME_EVT=evtMenuWelcome${COUNTRY})
    same => n,Answer()
    ;same => n,Set(CHANNEL(audio-features)=rate=16000,format=s16)
    same => n,Set(TALK_DETECT(set)=1500,128) 
    same => n,NoOp(Talk detection ENABLED on this channel for external monitoring.)
    same => n,Wait(2)
    same => n,AudioFork(ws://localhost:8081/${UNIQUEID}/botid-1/en-IN)
    ;same => n,Wait(1) ; Short wait after enabling detection
    same => n,Stasis(loony,botid-1,en-IN)
    ;same => n,StopAudioFork()
    ;same => n,Hangup()
