[general]
enabled=yes
bindaddr=0.0.0.0
bindport=8088
# tlsenable=yes
# tlsbindaddr=0.0.0.0:8088
# tlscertfile=/etc/asterisk/asterisk.pem

[mimetypes]
.xml = text/xml
.txt = text/plain
.html = text/html
.css = text/css
.js = application/x-javascript
.json = application/json