[global]
type = global
user_agent = Asterisk-PJ

[transport-tcp]
type = transport
protocol = tcp
bind = 0.0.0.0

[1000]
type = endpoint
context = internal
transport = transport-tcp
disallow = all
allow = ulaw
allow = alaw
auth = auth1000
aors = 1000

[auth1000]
type = auth
auth_type = userpass
username = 1000
password = password

[1000]
type = aor
max_contacts = 1